### ISSUE TITLE
Login Issue in Browser-Sign-In

### ISSUE THREAD

**Issue by chinmayk3** [okta/samples-js-react-native#104]
I am trying to click on Login Button , But nothing happen . No response in terminal also even after using all proper credentials . I am looking for browser-sign in react native using okta. Help me!!

**Comment by oleggnidets-okta** [comment]
Hey @chinmayk3,
Sorry to hear you meet the issue with our SDK. 

Did you follow the guide to set up the project https://developer.okta.com/docs/guides/sign-into-mobile-app/react-native/main/?

**Comment by chinmayk3** [comment]
Hi @oleggnidets-okta  , 
I have followed this one also but still same issue . Nothing happen after clicking on '**LOGIN**' button. No response in terminal.

**Comment by chinmayk3** [comment]
### **This credentials I am using to authenticate**
`   clientId: "0oa2XXXXXXX2Pp5d7", // e.g.: `a0abcEf0gH123ssJS4o5`
    redirectUri: "com.okta.dev-33XXXX47:/callback", // e.g.: `com.okta.example:/callback`
    endSessionRedirectUri: "com.okta.dev-33XXXX47:/logout", // e.g.: com.okta.example:/logout
    discoveryUri: "https://dev-33XXXX47.okta.com/oauth2/default", // e.g.: https://dev-1234.okta.com/oauth2 default
    scopes: ["openid", "profile", "offline_access"],
    requireHardwareBackedKeyStore: false,`

**Comment by NikitaAvraimov-okta** [comment]
Have you specified redirect uri for the native part, for example in android it is specified here: https://github.com/okta/samples-js-react-native/blob/e19894d208f060d0cf40700ead135421eddfae41/browser-sign-in/android/app/build.gradle#L138 also can you check if you have multiple apps installed on a device which are registered to the same uri. Otherwise we would need you to chech IDE stacktrace which may be more informative for our case

**Comment by chinmayk3** [comment]
Yes. I have added this one also.
`manifestPlaceholders = [
appAuthRedirectScheme: "com.okta.dev-3xxxxx47:/callback"
]`

**Comment by NikitaAvraimov-okta** [comment]
If no other app is installed than it`s very likely a problem with uri pattern, https://developer.okta.com/docs/guides/sampleapp-oie-redirectauth/android/main/#install-the-sample-app
> For example, if your redirect URI is com.okta.example:/callback, then the appAuthRedirectScheme should be com.okta.example.

**Comment by chinmayk3** [comment]
I have tried , this one also . But not working.

**Comment by oleggnidets-okta** [comment]
Are you running on Android or iOS? How do you run the app (via Android Studio/Xcode/Visual Studio/Terminal)?

**Comment by chinmayk3** [comment]
Android Emulator (Android Studio)

**Comment by chinmayk3** [comment]
Hi all , for testing purpose I have created application in developer okta console , thats working fine , I am able to redirect to uri (Okta Uri ). But when I use my organization's credentials then its not redirecting to the browser /uri . What should I do ?

**Comment by NikitaAvraimov-okta** [comment]
@chinmayk3 do you still require assistance? Were you able to sign in?

**Comment by oleggnidets-okta** [comment]
Close as no answer provided.
Feel free to reach out if you have any questions!
