### ISSUE TITLE
build.gradle maven repository needs to be updated. 

### ISSUE THREAD

**Issue by munkledata** [okta/samples-js-react-native#105]
The sample has this for the maven repository:         maven {
            url("https://dl.bintray.com/okta/com.okta.android")
        }

the instructions for okta react native (https://github.com/okta/okta-react-native#android-setup) is to use: 
mavenCentral()

bintray is dead service and is currently producing 502 bad gateways

**Comment by JayNewstrom** [comment]
Thanks for the heads up, I'll get it updated.
