### ISSUE TITLE
Auth Code Flow + PKCE question

### ISSUE THREAD

**Issue by reeinohio** [okta/samples-js-react-native#106]
This was referenced as an example for Auth Code Flow + PKCE
Does the @okta/okta-react-native module used here takes care of generating code verifier and code challenge, as well as passing them in appropriate request to okta (i.e. to get auth code, get access token)?   I didn't see in samples  react native code that it created code challenge and  code verifier.

**Comment by JayNewstrom** [comment]
Hi @reeinohio, yes, the SDK takes care of the handling of PKCE.
