### ISSUE TITLE
When you click Logout, you're prompted to "Sign In"

### ISSUE THREAD

**Issue by mraible** [okta/samples-js-react-native#14]
I don't think it's possible to change this message, but this is a surprising message for me as a user when I try to logout.

<img width="545" alt="Screen Shot 2019-09-20 at 11 53 32 AM" src="https://user-images.githubusercontent.com/17892/65347986-5e4d8d80-db9d-11e9-82ea-bc75da5f75dc.png">

**Comment by IldarAbdullin-okta** [comment]
Hi @mraible ,

You are right. It is not possible to change the message as it is a system dialog that was added in iOS 11 to 'ASWebAuthenticationSession' class and this class is used by the AppAuth iOS library. Currently there is no workaround found how to fix this message alert at least for sign out flow.

The same question was asked in Apple developer forum. No solution so far:
https://forums.developer.apple.com/thread/116421
https://forums.developer.apple.com/thread/91647

Ildar
