### ISSUE TITLE
Error in getAccessToken

### ISSUE THREAD

**Issue by maoapp** [okta/samples-js-react-native#27]
Hello guys,
I am Getting this error when I run getAccessToken
![image](https://user-images.githubusercontent.com/19539930/70656254-bbe6f880-1c27-11ea-83f9-48523f54f893.png)

anyone has faced it

Thanks in advance!

**Comment by jdnichollsc** [comment]
In Nordstrom team we're getting this other error:
> Authorization Error: Unexpected response format while retrieving authorization code.

<img width="584" alt="response format error" src="https://user-images.githubusercontent.com/2154886/70656415-0b2d2900-1c28-11ea-95d2-61e9374d02cf.png">

**Comment by maoapp** [comment]
@jdnichollsc I fixed the initial error and now I am facing the same than you

**Comment by swiftone** [comment]
Internal ref: OKTA-267180

**Comment by jdnichollsc** [comment]
Some logs from Xcode:
![image](https://user-images.githubusercontent.com/2154886/70944002-3052da80-2020-11ea-913e-4937541eb1f8.png)

**Comment by jdnichollsc** [comment]
ok guys, we're able to get the access token by configuring a deep link and fixing the redirection from the config to use that deep link, thanks! 👍

**Comment by IldarAbdullin-okta** [comment]
Hi @maoapp ,

Please make sure that you have properly configured OIDC SDK. I would recommend to play with [OIDC sample app](https://github.com/okta/samples-js-react-native/tree/master/browser-sign-in) first and check that you can get `access token` successfully

Ildar

**Comment by maoapp** [comment]
thanks for the support @IldarAbdullin-okta
