### ISSUE TITLE
App is crashing when the username/password is wrong

### ISSUE THREAD

**Issue by jdnichollsc** [okta/samples-js-react-native#28]
Hello guys,

We're debugging the customUI sample, but the app is crashing when the username/password is wrong executing the signIn method here https://github.com/okta/samples-js-react-native/blob/master/custom-sign-in/app/LoginScreen.js#L49

We want to get the error here https://github.com/okta/samples-js-react-native/blob/master/custom-sign-in/app/LoginScreen.js#L62 instead of closing the app with this native exception.

Thanks for your help!

**Comment by jdnichollsc** [comment]
Some screenshots:
- When the username/password is correct:
<img width="584" alt="Right credentials" src="https://user-images.githubusercontent.com/2154886/71225064-5ccb5880-22a5-11ea-8eaa-bc2b7e77ec16.png">
- When the username/password is wrong:
<img width="584" alt="Wrong credentials" src="https://user-images.githubusercontent.com/2154886/71225105-79679080-22a5-11ea-98a4-a2d1970f5bef.png">

**Comment by jdnichollsc** [comment]
Nevermind, It's working perfect! <3

**Comment by shubham-gupta-16** [comment]
Solution?
