### ISSUE TITLE
How to handle MFA workflow with custom-ui in my react-native app ?

### ISSUE THREAD

**Issue by kuldip9060** [okta/samples-js-react-native#29]
https://github.com/okta/okta-oidc-js/issues/652#issue-554637285

**Comment by swiftone** [comment]
Closing per related comment above in the react-native repo.

**Comment by IldarAbdullin-okta** [comment]
Hi @kuldip9060 ,

Please check the following [readme](https://github.com/okta/okta-auth-js). It contains very detailed info about how to trigger certain flows and handle MFAs.

Ildar
