### ISSUE TITLE
mjs breaks react-native app

### ISSUE THREAD

**Issue by garridio85** [okta/samples-js-react-native#45]
I am seeing an issue where the following library is causing a compile error:

Can't import the named export 'fromBase64Url' from non EcmaScript module (only default export is available)

If i remove the .mjs file it works perfectly but this shouldn't be the case.

Can anyone help?

**Comment by shuowu** [comment]
@garridio85 Looks like `.mjs` is still not supported in metro (https://github.com/facebook/metro/issues/535). Can you try to change the file type to `.js` instead?

**Comment by JayNewstrom** [comment]
Looks like Shuo was able to answer your question. If you have any others feel free to comment, reopen, or create a new issue. Thanks!
