### ISSUE TITLE
old version of npm package Detox causes build to fail

### ISSUE THREAD

**Issue by stevenbarash** [okta/samples-js-react-native#56]
System:
Mac OS X 10.15.7
Xcode 12.1
Node v14.14.0
NPM 6.14.8

Build fails with the errors below with the original version
[2020-10-22T20_21_57_248Z-debug.log](https://github.com/okta/samples-js-react-native/files/5429755/2020-10-22T20_21_57_248Z-debug.log)

`npm ERR! Failed at the detox@13.2.0 postinstall script.
`
Build succeeds after updating the package

**Comment by stevenbarash** [comment]
Fixed in pull request #55

**Comment by swiftone** [comment]
Note for anyone looking at this issue: discussion happening inside #55 rather than here so far

**Comment by JayNewstrom** [comment]
This was fixed in eff8fbaee5b2ab95f211d14a23825267bdc054f8
