### ISSUE TITLE
Help with -600 Okta Oidc error?

### ISSUE THREAD

**Issue by pblaha1138** [okta/samples-js-react-native#73]
Hello,

I'm having an issue getting this example to work properly. Upon entering the correct login information, the app throws a error with code -600 (Okta Oidc Error). Looking at the admin logs shows that okta believes a successful login occurred. I have reached the same issue working with both browser sign in and custom sign in. I am using an Android device running Android 10. I read posts in the developer forums that mentioned building a new virtual device solved the problem, but the same error has been thrown on my physical device, and three different virtual devices. 
Has anyone run into this issue and resolved it? It seems very odd that okta reads the interaction as a success, but library receives an error.

**Comment by JayNewstrom** [comment]
Hi @pblaha1138 can you confirm the redirect url is setup correctly in the admin dashboard as well as in the sample apps.

We've got some documentation for the Android portion here: https://github.com/okta/okta-react-native#add-redirect-scheme

**Comment by pblaha1138** [comment]
Hi @JayNewstrom,
I would love to confirm that, but not quite 100% sure that I can. Currently I have appAuthRedirectScheme set to "com.oktapreview.dev-XXXXXX"
Does that look like the right format?
I believe the app is set up correctly in the admin dashboard as well, but if you could be more specific on where it might have gone wrong to create this particular issue I would appreciate the help. 
Again, there is no indication that anything has gone wrong in the admin logs- everything reads as a success there.

**Comment by JayNewstrom** [comment]
That does look like the right format. In the okta admin dashboard under Applications -> General -> Login redirect URIs you should have a value along the lines of `com.oktapreview.dev-XXXXXX:/callback`

**Comment by khalidahmada** [comment]
I have the same issue : 

{error_message: "Authorization error", error_code: "-600"}

**Comment by oleggnidets-okta** [comment]
@khalidahmada Please, provide steps to reproduce. 
May I ask you to switch to branch `ognidets_OKTA-231724_Setup-e2e-test-runner-for-react-native-sample-applications` and try there as well?

**Comment by pblaha1138** [comment]
I can then confirm that those are correct- or at least that they follow that format and match. However, during my testing I have found that sometimes (not each time, and it seems to be new since last week), the System Log does show some error. When this happens, it logs three events. The first is a "User login to Okta" which is a success. Then "Evaluation of sign-on policy" which is allow. Finally, "OAuth2 authorization request" which reads "failure : user_not_assigned"

@oleggnidets-okta I switched to that branch, with no change.

**Comment by oleggnidets-okta** [comment]
`user_not_assigned` means a user is not assigned to the application. Go to admin console -> Applications -> {your app} -> Assignments -> Assign -> Assign to People -> Select your user. There's [the tutorial](https://help.okta.com/en/prod/Content/Topics/users-groups-profiles/usgp-assign-apps.htm).

**Comment by pblaha1138** [comment]
Thanks so much! I believe that that has helped. There's no change from the client's perspective still, but now instead of three events being generated per login attempt we're up to five. "OAuth2 authorization code request" is now a success, but "Claim evaluation for OAuth2 token failure" is user_claim_evaluation_failure, and "OAuth2 token request" is a system_claim_evaluation_failure. I'm assuming these are also based on how the app is configured on the admin side?

**Comment by oleggnidets-okta** [comment]
I am not sure what is a solution for the given errors, so far I found some topics on our Support Center:
- [Limitations of Group functions - Dynamic Whitelists](https://support.okta.com/help/s/article/Limitations-of-Group-functions-Dynamic-Whitelists?language=en_US)
- [How to investigate for login errors](https://devforum.okta.com/t/how-to-investigate-for-login-errors/6401)

Feel free to ask any question our [Support Team](https://support.okta.com/help/s/?language=en_US).
