### ISSUE TITLE
Error: Your Okta URL is missing

### ISSUE THREAD

**Issue by ShaikhSuf** [okta/samples-js-react-native#81]
Hi,

I followed the instructions in the repository and set up the dev environment as follows:-

CLIENT_ID=0oa1095cz1xzfghressa
REDIRECT_URI=com.okta.dev-71921545:/callback
LOGOUT_REDIRECT_URI=com.okta.dev-71921545:/callback
ISSUER=https://dev-71921545.okta.com/oauth2/default

But still getting the “Error: Your Okta URL is missing” error.

Thanks,
-Sufian

**Comment by mraible** [comment]
Where did you get these instructions? In the README's [configuration section](https://github.com/okta/samples-js-react-native#configuration), it says to put the values in `samples.config.js`:

```
export default {
  oidc: {
    clientId: '{clientId}',
    discoveryUri: 'https://{yourOktaDomain}/oauth2/default', // https://dev-1234.oktapreview.com/oauth2/default
    redirectUri: 'com.okta.{example}:/callback', // com.oktapreview.dev-1234:/callback
    endSessionRedirectUri: 'com.okta.{example}:/logoutCallback', // com.oktapreview.dev-1234:/logoutCallback
    scope: ["openid", "profile", "offline_access"],
    requireHardwareBackedKeyStore: false
  }
};
```

You could also try installing the [Okta CLI](https://cli.okta.com) and running `okta start react-native`. Here's a 3-minute video that shows how it works:

https://www.youtube.com/watch?v=jUOjIw-NBJ0

**Comment by ShaikhSuf** [comment]
samples.config.js from the repo looks like as as follows - 

import { CLIENT_ID, REDIRECT_URI, LOGOUT_REDIRECT_URI, ISSUER } from '@env'; 

export default {
  oidc: {
    clientId: CLIENT_ID, // e.g.: `a0abcEf0gH123ssJS4o5`
    redirectUri: REDIRECT_URI, // e.g.: `com.okta.example:/callback`
    endSessionRedirectUri: LOGOUT_REDIRECT_URI, // e.g.: com.okta.example:/logout
    discoveryUri: ISSUER, // e.g.: https://dev-1234.okta.com/oauth2/default
    scopes: ['openid', 'profile', 'offline_access'], 
    requireHardwareBackedKeyStore: false,
  },
};

So, I created a .env file and defined those env variables.

**Comment by oleggnidets-okta** [comment]
@ShaikhSuf You can replace the values directly. No need to use `.env` file. 
`.env` file is used for CI purposes. Probably, I'll update README to follow the latest changes.

**Comment by oleggnidets-okta** [comment]
I've updated README. Thanks @ShaikhSuf for bringing our attention to the issue.
